name: CI Tests

env:
  HOME: /root

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Vitest tests
      run: npm test
      
    - name: Run Playwright tests
      run: npx playwright test
      
    - name: Upload Vitest coverage report
      uses: actions/upload-artifact@v4
      if: always() && matrix.node-version == '22.x'
      with:
        name: vitest-coverage
        path: coverage/
        retention-days: 30
        
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always() && matrix.node-version == '22.x'
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30