name: Cypress E2E Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  basic:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2025, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:5173
          start: npx vite --host